### ISSUE TITLE
Error in datasource app studio "An error occurred retrieving service(s) for SAP System"

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-devtoberfest-2020#51]
Hi @IObert , I'm facing an issue retrieving the services from my destination, take a look of the following screenshot.

![image](https://user-images.githubusercontent.com/10300948/93474732-5cf09700-f8bd-11ea-98e9-718a0c7de8e7.png)

I configured the destination as the tutorials said.

![image](https://user-images.githubusercontent.com/10300948/93475005-bd7fd400-f8bd-11ea-9051-151d663a2fba.png)

![image](https://user-images.githubusercontent.com/10300948/93475067-ce304a00-f8bd-11ea-9572-239c173779be.png)

What could be wrong here?

Thank you.

Jhon Jairo Teran.

**Comment by IObert** [comment]
Hi,

It seems there is currently something wrong with the Business Application Studio. I get the same message and it also fails when I try to connect directly to `https://sapes5.sapdevcenter.com/sap/opu/odata/sap/SEPMRA_PROD_MAN` (as shown in the video). The backend system itself is still available. Please try again later or tomorrow.

Sorry for the inconvenience.

**Comment by jhonj98** [comment]
Ok, thanks. I'll try later.

**Comment by IObert** [comment]
The issue should be resolved now. Can you please try again?

**Comment by jhonj98** [comment]
Yes Marius!, now it's working well! I could finish the fiori app creation.

Thank you.

Jhon Jairo.

**Comment by shrikantpatil-git** [comment]
Hello,
I am getting authentication error 
![git](https://user-images.githubusercontent.com/84910730/119819395-f58bec00-bf0d-11eb-850d-94519b2cb300.PNG)

I configured the destination as the tutorials said.

Can you please guide me here

**Comment by IObert** [comment]
This error means you didn't enter the right password. But actually, the tutorial says you should use the destination but you entered the URL directly.

**Comment by shrikantpatil-git** [comment]
> This error means you didn't enter the right password. But actually, the tutorial says you should use the destination but you entered the URL directly.

I  have entered correct password infact I tried 3-4 times still getting the error. And can you please guide me about destination (in tutorial URL is used)

**Comment by IObert** [comment]
It should all be in here <https://github.com/SAP-samples/sap-devtoberfest-2020/tree/master/topics/appstudio>
